/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screens.inventory;

import java.util.HashMap;
import screens.administrator.AdministratorScreen;

/**
 *
 * @author ronny
 */
public class InventoryScreen extends javax.swing.JFrame {

    /**
     * Creates new form InventoryScreen
     */
    public InventoryScreen() {
        initComponents();
    }
    // bukan kurang nu, emg blm di bikin dialognya.. jd pada saat user klik menu report nnti ada dialog lagi
    //

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtFillterName = new javax.swing.JTextField();
        txtFillterName1 = new javax.swing.JTextField();
        txtFillterName2 = new javax.swing.JTextField();
        txtFillterName3 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblViewTickets = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        txtFillterName4 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btnAdd = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        btnCetak = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID");

        jLabel2.setText("NAMA");

        jLabel3.setText("HARGA");

        jLabel4.setText("JUMLAH");

        txtFillterName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFillterNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFillterNameFocusLost(evt);
            }
        });
        txtFillterName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFillterNameActionPerformed(evt);
            }
        });
        txtFillterName.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtFillterNamePropertyChange(evt);
            }
        });
        txtFillterName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFillterNameKeyPressed(evt);
            }
        });

        txtFillterName1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFillterName1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFillterName1FocusLost(evt);
            }
        });
        txtFillterName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFillterName1ActionPerformed(evt);
            }
        });
        txtFillterName1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtFillterName1PropertyChange(evt);
            }
        });
        txtFillterName1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFillterName1KeyPressed(evt);
            }
        });

        txtFillterName2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFillterName2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFillterName2FocusLost(evt);
            }
        });
        txtFillterName2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFillterName2ActionPerformed(evt);
            }
        });
        txtFillterName2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtFillterName2PropertyChange(evt);
            }
        });
        txtFillterName2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFillterName2KeyPressed(evt);
            }
        });

        txtFillterName3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFillterName3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFillterName3FocusLost(evt);
            }
        });
        txtFillterName3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFillterName3ActionPerformed(evt);
            }
        });
        txtFillterName3.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtFillterName3PropertyChange(evt);
            }
        });
        txtFillterName3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFillterName3KeyPressed(evt);
            }
        });

        tblViewTickets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblViewTickets);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtFillterName4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFillterName4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFillterName4FocusLost(evt);
            }
        });
        txtFillterName4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFillterName4ActionPerformed(evt);
            }
        });
        txtFillterName4.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtFillterName4PropertyChange(evt);
            }
        });
        txtFillterName4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFillterName4KeyPressed(evt);
            }
        });

        btnAdd.setText("Tambah");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jButton3.setText("Ubah");

        jButton4.setText("Hapus");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtFillterName4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(21, 21, 21))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(14, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(txtFillterName4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jMenu1.setText("Menu");

        jMenuItem1.setText("Ganti Password");
        jMenu1.add(jMenuItem1);

        btnCetak.setText("Cetak Laporan");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });
        jMenu1.add(btnCetak);

        jMenuItem3.setText("Keluar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtFillterName2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(12, 12, 12)
                        .addComponent(txtFillterName3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFillterName, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFillterName1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(36, 36, 36)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtFillterName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtFillterName1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtFillterName2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtFillterName3)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFillterNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFillterNameFocusGained
    }//GEN-LAST:event_txtFillterNameFocusGained

    private void txtFillterNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFillterNameFocusLost
    }//GEN-LAST:event_txtFillterNameFocusLost

    private void txtFillterNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFillterNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFillterNameActionPerformed

    private void txtFillterNamePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtFillterNamePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFillterNamePropertyChange

    private void txtFillterNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFillterNameKeyPressed
    }//GEN-LAST:event_txtFillterNameKeyPressed

    private void txtFillterName1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFillterName1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFillterName1FocusGained

    private void txtFillterName1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFillterName1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFillterName1FocusLost

    private void txtFillterName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFillterName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFillterName1ActionPerformed

    private void txtFillterName1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtFillterName1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFillterName1PropertyChange

    private void txtFillterName1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFillterName1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFillterName1KeyPressed

    private void txtFillterName2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFillterName2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFillterName2FocusGained

    private void txtFillterName2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFillterName2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFillterName2FocusLost

    private void txtFillterName2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFillterName2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFillterName2ActionPerformed

    private void txtFillterName2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtFillterName2PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFillterName2PropertyChange

    private void txtFillterName2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFillterName2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFillterName2KeyPressed

    private void txtFillterName3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFillterName3FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFillterName3FocusGained

    private void txtFillterName3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFillterName3FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFillterName3FocusLost

    private void txtFillterName3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFillterName3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFillterName3ActionPerformed

    private void txtFillterName3PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtFillterName3PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFillterName3PropertyChange

    private void txtFillterName3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFillterName3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFillterName3KeyPressed

    private void txtFillterName4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFillterName4FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFillterName4FocusGained

    private void txtFillterName4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFillterName4FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFillterName4FocusLost

    private void txtFillterName4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFillterName4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFillterName4ActionPerformed

    private void txtFillterName4PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtFillterName4PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFillterName4PropertyChange

    private void txtFillterName4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFillterName4KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFillterName4KeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    
    
    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        // TODO add your handling code here:
        AdministratorScreen obj = new AdministratorScreen();
        HashMap _hash = new HashMap();
        _hash.put("times","2021-05-17");
        obj.printOut("report_ShowInventory_Ketentuan.jasper",_hash);
        
        
    }//GEN-LAST:event_btnCetakActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InventoryScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InventoryScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InventoryScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InventoryScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InventoryScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JMenuItem btnCetak;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblViewTickets;
    private javax.swing.JTextField txtFillterName;
    private javax.swing.JTextField txtFillterName1;
    private javax.swing.JTextField txtFillterName2;
    private javax.swing.JTextField txtFillterName3;
    private javax.swing.JTextField txtFillterName4;
    // End of variables declaration//GEN-END:variables
}
