/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screens;

import core.services.AuthService;
import javax.swing.JOptionPane;
import screens.administrator.AdministratorScreen;

/**
 *
 * @author ronny
 */
public class UpdatePasswordScreen extends javax.swing.JFrame {

    /**
     * Creates new form UpdatePasswordScreen
     */
    private static int USER_ID;
    private static String TEMP_PASSWORD = "";

    AuthService authService = new AuthService();

    public UpdatePasswordScreen(int userId) {
        initComponents();
        // Init Configuration
        setLocationRelativeTo(null);
        lblNewPassword.setVisible(false);
        txtNewPassword.setVisible(false);
        btnChange.setVisible(false);
        setSize(302, 140);

        if (userId != 0) {
            USER_ID = userId;
            TEMP_PASSWORD = authService.getUser(USER_ID).getPassword();
            if (TEMP_PASSWORD.isEmpty()) {
                dispose();
            }
        } else {
            dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame = new javax.swing.JPanel();
        txtBack = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtLastPassword = new javax.swing.JTextField();
        lblLastPassword = new javax.swing.JLabel();
        txtNewPassword = new javax.swing.JTextField();
        lblNewPassword = new javax.swing.JLabel();
        btnChange = new javax.swing.JButton();
        lblMarkCopyright = new javax.swing.JLabel();
        btnCheck = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        setResizable(false);

        jFrame.setBackground(new java.awt.Color(255, 255, 255));

        txtBack.setFont(new java.awt.Font("Poppins", 0, 24)); // NOI18N
        txtBack.setText("<");
        txtBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBackMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Lato", 1, 12)); // NOI18N
        jLabel6.setText("CGC - Change Password");

        javax.swing.GroupLayout jFrameLayout = new javax.swing.GroupLayout(jFrame);
        jFrame.setLayout(jFrameLayout);
        jFrameLayout.setHorizontalGroup(
            jFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 302, Short.MAX_VALUE)
            .addGroup(jFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFrameLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(txtBack)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(62, Short.MAX_VALUE)))
        );
        jFrameLayout.setVerticalGroup(
            jFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
            .addGroup(jFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFrameLayout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addGroup(jFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtBack, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addContainerGap(10, Short.MAX_VALUE)))
        );

        txtLastPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLastPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLastPasswordFocusLost(evt);
            }
        });
        txtLastPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastPasswordActionPerformed(evt);
            }
        });
        txtLastPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLastPasswordKeyPressed(evt);
            }
        });

        lblLastPassword.setFont(new java.awt.Font("Poppins", 1, 10)); // NOI18N
        lblLastPassword.setText("Last Password");

        txtNewPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNewPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNewPasswordFocusLost(evt);
            }
        });
        txtNewPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewPasswordActionPerformed(evt);
            }
        });
        txtNewPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNewPasswordKeyPressed(evt);
            }
        });

        lblNewPassword.setFont(new java.awt.Font("Poppins", 1, 10)); // NOI18N
        lblNewPassword.setText("New Password");

        btnChange.setBackground(new java.awt.Color(153, 169, 193));
        btnChange.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnChange.setText("Change");
        btnChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeActionPerformed(evt);
            }
        });

        lblMarkCopyright.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        lblMarkCopyright.setForeground(new java.awt.Color(102, 102, 102));
        lblMarkCopyright.setText("Copyright 2021 - Devloid Indonesia");

        btnCheck.setText("Check");
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMarkCopyright, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(txtLastPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addComponent(lblLastPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(84, 84, 84))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(5, 5, 5)
                                    .addComponent(lblNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(btnChange, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblLastPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLastPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCheck))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnChange, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblMarkCopyright, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBackMouseClicked
        AdministratorScreen _admScreen = new AdministratorScreen(USER_ID);
        _admScreen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_txtBackMouseClicked

    private void txtLastPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLastPasswordFocusGained

        if (this.txtLastPassword.getText().equals("Enter your last password")) {
            this.txtLastPassword.setText("");
        }
    }//GEN-LAST:event_txtLastPasswordFocusGained

    private void txtLastPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLastPasswordFocusLost
        if (this.txtLastPassword.getText().isEmpty()) {
            this.txtLastPassword.setText("Enter your last password");
        }
    }//GEN-LAST:event_txtLastPasswordFocusLost

    private void txtLastPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastPasswordActionPerformed

    private void txtLastPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLastPasswordKeyPressed

    }//GEN-LAST:event_txtLastPasswordKeyPressed

    private void txtNewPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNewPasswordFocusGained
        if (this.txtNewPassword.getText().equals("Enter your new password")) {
            this.txtNewPassword.setText("");
        }
    }//GEN-LAST:event_txtNewPasswordFocusGained

    private void txtNewPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNewPasswordFocusLost
        if (this.txtNewPassword.getText().isEmpty()) {
            this.txtNewPassword.setText("Enter your new password");
        }
    }//GEN-LAST:event_txtNewPasswordFocusLost

    private void txtNewPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewPasswordActionPerformed

    private void txtNewPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNewPasswordKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewPasswordKeyPressed

    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeActionPerformed
        String _password = txtNewPassword.getText();
        if (!_password.isEmpty()) {
            authService.updatePassword(USER_ID, _password);
            JOptionPane.showMessageDialog(this, "Password Berhasil Di Perbaharui.");
            SignInScreen _signInScreen = new SignInScreen();
            _signInScreen.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Oops! Password Baru Tidak Boleh Kosong.");
        }

    }//GEN-LAST:event_btnChangeActionPerformed

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
        if (!txtLastPassword.getText().isEmpty() && !txtLastPassword.getText().equals("Enter your last password")) {

            if (TEMP_PASSWORD.equals(txtLastPassword.getText())) {
                // Hide last component
                lblLastPassword.setVisible(false);
                txtLastPassword.setVisible(false);
                btnCheck.setVisible(false);
                // Show new component
                lblNewPassword.setVisible(true);
                txtNewPassword.setVisible(true);
                btnChange.setVisible(true);
                this.setSize(302, 230);

            }

        }

    }//GEN-LAST:event_btnCheckActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdatePasswordScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdatePasswordScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdatePasswordScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdatePasswordScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new UpdatePasswordScreen(USER_ID).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChange;
    private javax.swing.JButton btnCheck;
    private javax.swing.JPanel jFrame;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblLastPassword;
    private javax.swing.JLabel lblMarkCopyright;
    private javax.swing.JLabel lblNewPassword;
    private javax.swing.JLabel txtBack;
    private javax.swing.JTextField txtLastPassword;
    private javax.swing.JTextField txtNewPassword;
    // End of variables declaration//GEN-END:variables
}
